name: Simple CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Run a hello world script
      run: echo "Hello, GitHub Actions is now working!"
